<?php

// $total = 5322;

$take = 100;

$total = 1;
$current = 0;

$userID = "cdda04ea-08c3-45f6-b7cf-25fd564e509d";

$query = 'mutation insertBook($book: book_input!) {
    book(book: $book) {
        id
    }
}';
while ($current < $total) {
    $data = json_decode(file_get_contents("https://adam:test@comicbox.ca/book?skip=$current&count=$take"));
    $total = $data->number;
    $current += count($data->books);
    foreach($data->books as $book) {
        $variables = [
            'book' => [
                "series"           => $book->series,
                "file"             => $book->file,
                "authors"          => explode(",", $book->author),
                "last_page_read"   => $book->last_page_read,
                "alternate_series" => $book->alternate_series,
                "chapter"          => $book->number != 0 ? $book->number : null,
                "type"             => $book->type,
                "current_page"     => $book->current_page,
                "story_arc"        => $book->story_arc,
                "pages"            => $book->pages,
                "volume"           => $book->volume != 0 ? $book->volume : null,
                "genres"           => explode(",", $book->genre),
                "rating"           => $book->rating,
                "web"              => $book->web,
                "title"            => $book->title,
                "community_rating" => $book->community_rating,
                "date_released"    => $book->date_released,
                "summary"          => $book->summary,
            ],
        ];

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, "http://localhost:8080/graphql");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode([
            "query"     => $query,
            "variables" => $variables,
        ]));
        curl_setopt($ch, CURLOPT_POST, 1);

        $headers = array();
        $headers[] = "Content-Type: application/json";
        $headers[] = "x-user: $userID";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close ($ch);
        print_r($result);
    }
}