// Code generated by go-bindata. DO NOT EDIT. @generated
// sources:
// ../comicboxd/migrations/10000_seed.down.sql
// ../comicboxd/migrations/10000_seed.up.sql
// ../comicboxd/migrations/1_create_book_user_and_user_book.down.sql
// ../comicboxd/migrations/1_create_book_user_and_user_book.up.sql
// ../comicboxd/migrations/2_add_series_tags.down.sql
// ../comicboxd/migrations/2_add_series_tags.up.sql
// dist/658dde714e624426b1f0f9976f031513.woff2
// dist/index.html
// dist/main.css
// dist/main.js
package data

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// ComicboxdMigrations10000_seedDownSql reads file data from disk. It returns an error on failure.
func ComicboxdMigrations10000_seedDownSql() (*asset, error) {
	path := "/home/adam/go/src/github.com/zwzn/comicbox/comicboxd/migrations/10000_seed.down.sql"
	name := "../comicboxd/migrations/10000_seed.down.sql"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// ComicboxdMigrations10000_seedUpSql reads file data from disk. It returns an error on failure.
func ComicboxdMigrations10000_seedUpSql() (*asset, error) {
	path := "/home/adam/go/src/github.com/zwzn/comicbox/comicboxd/migrations/10000_seed.up.sql"
	name := "../comicboxd/migrations/10000_seed.up.sql"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// ComicboxdMigrations1_create_book_user_and_user_bookDownSql reads file data from disk. It returns an error on failure.
func ComicboxdMigrations1_create_book_user_and_user_bookDownSql() (*asset, error) {
	path := "/home/adam/go/src/github.com/zwzn/comicbox/comicboxd/migrations/1_create_book_user_and_user_book.down.sql"
	name := "../comicboxd/migrations/1_create_book_user_and_user_book.down.sql"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// ComicboxdMigrations1_create_book_user_and_user_bookUpSql reads file data from disk. It returns an error on failure.
func ComicboxdMigrations1_create_book_user_and_user_bookUpSql() (*asset, error) {
	path := "/home/adam/go/src/github.com/zwzn/comicbox/comicboxd/migrations/1_create_book_user_and_user_book.up.sql"
	name := "../comicboxd/migrations/1_create_book_user_and_user_book.up.sql"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// ComicboxdMigrations2_add_series_tagsDownSql reads file data from disk. It returns an error on failure.
func ComicboxdMigrations2_add_series_tagsDownSql() (*asset, error) {
	path := "/home/adam/go/src/github.com/zwzn/comicbox/comicboxd/migrations/2_add_series_tags.down.sql"
	name := "../comicboxd/migrations/2_add_series_tags.down.sql"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// ComicboxdMigrations2_add_series_tagsUpSql reads file data from disk. It returns an error on failure.
func ComicboxdMigrations2_add_series_tagsUpSql() (*asset, error) {
	path := "/home/adam/go/src/github.com/zwzn/comicbox/comicboxd/migrations/2_add_series_tags.up.sql"
	name := "../comicboxd/migrations/2_add_series_tags.up.sql"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dist658dde714e624426b1f0f9976f031513Woff2 reads file data from disk. It returns an error on failure.
func dist658dde714e624426b1f0f9976f031513Woff2() (*asset, error) {
	path := "/home/adam/go/src/github.com/zwzn/comicbox/web/dist/658dde714e624426b1f0f9976f031513.woff2"
	name := "dist/658dde714e624426b1f0f9976f031513.woff2"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// distIndexHtml reads file data from disk. It returns an error on failure.
func distIndexHtml() (*asset, error) {
	path := "/home/adam/go/src/github.com/zwzn/comicbox/web/dist/index.html"
	name := "dist/index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// distMainCss reads file data from disk. It returns an error on failure.
func distMainCss() (*asset, error) {
	path := "/home/adam/go/src/github.com/zwzn/comicbox/web/dist/main.css"
	name := "dist/main.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// distMainJs reads file data from disk. It returns an error on failure.
func distMainJs() (*asset, error) {
	path := "/home/adam/go/src/github.com/zwzn/comicbox/web/dist/main.js"
	name := "dist/main.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"../comicboxd/migrations/10000_seed.down.sql": ComicboxdMigrations10000_seedDownSql,
	"../comicboxd/migrations/10000_seed.up.sql": ComicboxdMigrations10000_seedUpSql,
	"../comicboxd/migrations/1_create_book_user_and_user_book.down.sql": ComicboxdMigrations1_create_book_user_and_user_bookDownSql,
	"../comicboxd/migrations/1_create_book_user_and_user_book.up.sql": ComicboxdMigrations1_create_book_user_and_user_bookUpSql,
	"../comicboxd/migrations/2_add_series_tags.down.sql": ComicboxdMigrations2_add_series_tagsDownSql,
	"../comicboxd/migrations/2_add_series_tags.up.sql": ComicboxdMigrations2_add_series_tagsUpSql,
	"dist/658dde714e624426b1f0f9976f031513.woff2": dist658dde714e624426b1f0f9976f031513Woff2,
	"dist/index.html": distIndexHtml,
	"dist/main.css": distMainCss,
	"dist/main.js": distMainJs,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"..": &bintree{nil, map[string]*bintree{
		"comicboxd": &bintree{nil, map[string]*bintree{
			"migrations": &bintree{nil, map[string]*bintree{
				"10000_seed.down.sql": &bintree{ComicboxdMigrations10000_seedDownSql, map[string]*bintree{}},
				"10000_seed.up.sql": &bintree{ComicboxdMigrations10000_seedUpSql, map[string]*bintree{}},
				"1_create_book_user_and_user_book.down.sql": &bintree{ComicboxdMigrations1_create_book_user_and_user_bookDownSql, map[string]*bintree{}},
				"1_create_book_user_and_user_book.up.sql": &bintree{ComicboxdMigrations1_create_book_user_and_user_bookUpSql, map[string]*bintree{}},
				"2_add_series_tags.down.sql": &bintree{ComicboxdMigrations2_add_series_tagsDownSql, map[string]*bintree{}},
				"2_add_series_tags.up.sql": &bintree{ComicboxdMigrations2_add_series_tagsUpSql, map[string]*bintree{}},
			}},
		}},
	}},
	"dist": &bintree{nil, map[string]*bintree{
		"658dde714e624426b1f0f9976f031513.woff2": &bintree{dist658dde714e624426b1f0f9976f031513Woff2, map[string]*bintree{}},
		"index.html": &bintree{distIndexHtml, map[string]*bintree{}},
		"main.css": &bintree{distMainCss, map[string]*bintree{}},
		"main.js": &bintree{distMainJs, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

