export const app: string;
export const parallaxWrap: string;
export const search: string;
export const main: string;
export const bottomBar: string;
export const link: string;
export const active: string;
export const icon: string;
export const title: string;
