export const header: string;
export const cover: string;
export const rating: string;
export const series: string;
export const title: string;
export const readFab: string;
export const summary: string;
export const books: string;
export const background: string;
